import type { Courier, MenuItem, OrderWithCourier, Restaurant } from './types';

const t = (minsAgo: number) =>
  new Date(Date.now() - minsAgo * 60_000).toISOString();

export const mockRestaurant: Restaurant = {
  id: 'rest-001',
  user_id: 'user-001',
  name: 'Kebapçı Mehmet Usta',
  address: 'Barbaros Bulvarı No:45, Beşiktaş, İstanbul',
  lat: 41.0422,
  lng: 29.0044,
  phone: '+90 212 555 0100',
  avg_prep_time_minutes: 20,
  created_at: new Date('2024-01-01').toISOString(),
};

export const mockCouriers: Courier[] = [
  {
    id: 'courier-001',
    user_id: 'user-002',
    restaurant_id: 'rest-001',
    name: 'Mehmet Kaya',
    phone: '+90 532 111 2233',
    vehicle_type: 'motorcycle',
    is_active: true,
    is_available: true,
    current_lat: 41.045,
    current_lng: 29.006,
    last_seen_at: t(2),
    created_at: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'courier-002',
    user_id: 'user-003',
    restaurant_id: 'rest-001',
    name: 'Ali Demir',
    phone: '+90 533 444 5566',
    vehicle_type: 'motorcycle',
    is_active: true,
    is_available: true,
    current_lat: 41.038,
    current_lng: 29.012,
    last_seen_at: t(5),
    created_at: new Date('2024-02-01').toISOString(),
  },
  {
    id: 'courier-003',
    user_id: 'user-004',
    restaurant_id: null,
    name: 'Hasan Yıldız',
    phone: '+90 534 777 8899',
    vehicle_type: 'bicycle',
    is_active: false,
    is_available: false,
    current_lat: null,
    current_lng: null,
    last_seen_at: t(120),
    created_at: new Date('2024-02-15').toISOString(),
  },
];

export const MOCK_MENU_ITEMS: MenuItem[] = [
  // Ana Yemekler
  { id: 'menu-01', restaurant_id: 'rest-001', category: 'Ana Yemekler', name: 'Adana Kebap', description: '300g el yapımı köy biberi kebabı, lavash, közlenmiş domates', price: 185, is_available: true, created_at: new Date('2024-01-01').toISOString() },
  { id: 'menu-02', restaurant_id: 'rest-001', category: 'Ana Yemekler', name: 'Tavuk Şiş', description: 'Marine edilmiş ızgara tavuk, pilav ve salata', price: 145, is_available: true, created_at: new Date('2024-01-01').toISOString() },
  { id: 'menu-03', restaurant_id: 'rest-001', category: 'Ana Yemekler', name: 'Köfte Tabağı', description: 'Izgara köfte, patates kızartması, közlenmiş biber', price: 130, is_available: true, created_at: new Date('2024-01-01').toISOString() },
  { id: 'menu-04', restaurant_id: 'rest-001', category: 'Ana Yemekler', name: 'Lahmacun (3 Adet)', description: 'İnce hamur, kıymalı harç, yanında limon ve maydanoz', price: 90, is_available: true, created_at: new Date('2024-01-01').toISOString() },
  { id: 'menu-05', restaurant_id: 'rest-001', category: 'Ana Yemekler', name: 'İskender Kebap', description: 'Döner üzeri yoğurt, domates sosu ve tereyağı', price: 210, is_available: true, created_at: new Date('2024-01-01').toISOString() },
  // Başlangıçlar
  { id: 'menu-06', restaurant_id: 'rest-001', category: 'Başlangıçlar', name: 'Mercimek Çorbası', description: 'Geleneksel kırmızı mercimek çorbası, limon ve nane', price: 55, is_available: true, created_at: new Date('2024-01-01').toISOString() },
  { id: 'menu-07', restaurant_id: 'rest-001', category: 'Başlangıçlar', name: 'Humus', description: 'Tahin, limon ve zeytinyağı ile hazırlanan nohut ezmesi', price: 65, is_available: true, created_at: new Date('2024-01-01').toISOString() },
  { id: 'menu-08', restaurant_id: 'rest-001', category: 'Başlangıçlar', name: 'Sigara Böreği (6 Adet)', description: 'Peynirli ince yufka böreği, çıtır kızartma', price: 75, is_available: true, created_at: new Date('2024-01-01').toISOString() },
  { id: 'menu-09', restaurant_id: 'rest-001', category: 'Başlangıçlar', name: 'Patlıcan Ezmesi', description: 'Közlenmiş patlıcan, sarımsak, zeytinyağı', price: 60, is_available: true, created_at: new Date('2024-01-01').toISOString() },
  // İçecekler
  { id: 'menu-10', restaurant_id: 'rest-001', category: 'İçecekler', name: 'Ayran', description: 'Taze çırpılmış ayran, 250ml', price: 20, is_available: true, created_at: new Date('2024-01-01').toISOString() },
  { id: 'menu-11', restaurant_id: 'rest-001', category: 'İçecekler', name: 'Kola', description: 'Soğuk içecek, 330ml', price: 25, is_available: true, created_at: new Date('2024-01-01').toISOString() },
  { id: 'menu-12', restaurant_id: 'rest-001', category: 'İçecekler', name: 'Su', description: 'Pet şişe su, 500ml', price: 10, is_available: true, created_at: new Date('2024-01-01').toISOString() },
  { id: 'menu-13', restaurant_id: 'rest-001', category: 'İçecekler', name: 'Şalgam', description: 'Acılı veya acısız şalgam suyu, 250ml', price: 20, is_available: true, created_at: new Date('2024-01-01').toISOString() },
  // Tatlılar
  { id: 'menu-14', restaurant_id: 'rest-001', category: 'Tatlılar', name: 'Baklava (3 Dilim)', description: 'Antep fıstıklı baklava, özel şerbet', price: 95, is_available: true, created_at: new Date('2024-01-01').toISOString() },
  { id: 'menu-15', restaurant_id: 'rest-001', category: 'Tatlılar', name: 'Sütlaç', description: 'Fırın sütlaç, tarçın ile servis edilir', price: 65, is_available: true, created_at: new Date('2024-01-01').toISOString() },
  { id: 'menu-16', restaurant_id: 'rest-001', category: 'Tatlılar', name: 'Kadayıf', description: 'Sade kadayıf, dondurmalı veya sade', price: 80, is_available: true, created_at: new Date('2024-01-01').toISOString() },
];

export const mockOrders: OrderWithCourier[] = [
  {
    id: 'order-001',
    restaurant_id: 'rest-001',
    courier_id: 'courier-001',
    platform: 'yemeksepeti',
    platform_order_id: 'YS-8821943',
    customer_name: 'Ahmet Yılmaz',
    customer_address: 'Nispetiye Cad. 12/3, Etiler, İstanbul',
    customer_lat: 41.079,
    customer_lng: 29.035,
    status: 'picked_up',
    total_amount: 284.9,
    payment_method: 'online_paid',
    payment_status: 'not_required',
    created_at: t(22),
    assigned_at: t(18),
    picked_up_at: t(8),
    delivered_at: null,
    courier: mockCouriers[0],
  },
  {
    id: 'order-002',
    restaurant_id: 'rest-001',
    courier_id: 'courier-002',
    platform: 'getir',
    platform_order_id: 'GT-4490217',
    customer_name: 'Zeynep Arslan',
    customer_address: 'Bağdat Cad. 88, Kadıköy, İstanbul',
    customer_lat: 40.9773,
    customer_lng: 29.0678,
    status: 'assigned',
    total_amount: 156.5,
    payment_method: 'cash',
    payment_status: 'pending',
    created_at: t(12),
    assigned_at: t(8),
    picked_up_at: null,
    delivered_at: null,
    courier: mockCouriers[1],
  },
  {
    id: 'order-003',
    restaurant_id: 'rest-001',
    courier_id: null,
    platform: 'trendyol',
    platform_order_id: 'TY-3301889',
    customer_name: 'Fatma Şahin',
    customer_address: 'Halaskargazi Cad. 55/7, Şişli, İstanbul',
    customer_lat: 41.062,
    customer_lng: 28.987,
    status: 'pending',
    total_amount: 89.9,
    payment_method: 'online_paid',
    payment_status: 'not_required',
    created_at: t(5),
    assigned_at: null,
    picked_up_at: null,
    delivered_at: null,
    courier: null,
  },
  {
    id: 'order-004',
    restaurant_id: 'rest-001',
    courier_id: 'courier-001',
    platform: 'yemeksepeti',
    platform_order_id: 'YS-8819201',
    customer_name: 'Murat Öztürk',
    customer_address: 'Ihlamurdere Cad. 22, Beşiktaş, İstanbul',
    customer_lat: 41.0482,
    customer_lng: 29.0012,
    status: 'delivered',
    total_amount: 445.0,
    payment_method: 'online_paid',
    payment_status: 'not_required',
    created_at: t(90),
    assigned_at: t(85),
    picked_up_at: t(72),
    delivered_at: t(45),
    courier: mockCouriers[0],
  },
  {
    id: 'order-005',
    restaurant_id: 'rest-001',
    courier_id: null,
    platform: 'pakettaksi',
    platform_order_id: 'PT-112934',
    customer_name: 'Selin Kara',
    customer_address: 'Teşvikiye Cad. 7/2, Nişantaşı, İstanbul',
    customer_lat: 41.0528,
    customer_lng: 28.9944,
    status: 'pending',
    total_amount: 210.0,
    payment_method: 'card',
    payment_status: 'pending',
    created_at: t(3),
    assigned_at: null,
    picked_up_at: null,
    delivered_at: null,
    courier: null,
  },
  {
    id: 'order-006',
    restaurant_id: 'rest-001',
    courier_id: 'courier-002',
    platform: 'getir',
    platform_order_id: 'GT-4488901',
    customer_name: 'Emre Yılmaz',
    customer_address: 'Sinanpaşa Cad. 14, Beşiktaş, İstanbul',
    customer_lat: 41.046,
    customer_lng: 29.008,
    status: 'picked_up',
    total_amount: 127.5,
    payment_method: 'online_paid',
    payment_status: 'not_required',
    created_at: t(35),
    assigned_at: t(30),
    picked_up_at: t(15),
    delivered_at: null,
    courier: mockCouriers[1],
  },
  {
    id: 'order-007',
    restaurant_id: 'rest-001',
    courier_id: null,
    platform: 'manual',
    platform_order_id: null,
    customer_name: 'Deniz Acar',
    customer_address: 'Ortabahçe Cad. 33, Beşiktaş, İstanbul',
    customer_lat: 41.0402,
    customer_lng: 29.005,
    status: 'pending',
    total_amount: 340.0,
    payment_method: 'cash',
    payment_status: 'pending',
    created_at: t(8),
    assigned_at: null,
    picked_up_at: null,
    delivered_at: null,
    courier: null,
  },
  {
    id: 'order-008',
    restaurant_id: 'rest-001',
    courier_id: 'courier-001',
    platform: 'trendyol',
    platform_order_id: 'TY-3298744',
    customer_name: 'Ayşe Güler',
    customer_address: 'Barbaros Bulvarı No:78, Balmumcu, İstanbul',
    customer_lat: 41.0511,
    customer_lng: 29.0108,
    status: 'delivered',
    total_amount: 195.0,
    payment_method: 'cash',
    payment_status: 'collected',
    payment_collected_at: t(62),
    created_at: t(120),
    assigned_at: t(115),
    picked_up_at: t(100),
    delivered_at: t(65),
    courier: mockCouriers[0],
  },
];
