import type { Courier, OrderWithCourier, Restaurant } from './types';

const t = (minsAgo: number) =>
  new Date(Date.now() - minsAgo * 60_000).toISOString();

export const mockRestaurant: Restaurant = {
  id: 'rest-001',
  user_id: 'user-001',
  name: 'Kebapçı Mehmet Usta',
  address: 'Barbaros Bulvarı No:45, Beşiktaş, İstanbul',
  lat: 41.0422,
  lng: 29.0044,
  phone: '+90 212 555 0100',
  created_at: new Date('2024-01-01').toISOString(),
};

export const mockCouriers: Courier[] = [
  {
    id: 'courier-001',
    user_id: 'user-002',
    name: 'Mehmet Kaya',
    phone: '+90 532 111 2233',
    vehicle_type: 'motorcycle',
    is_active: true,
    current_lat: 41.045,
    current_lng: 29.006,
    last_seen_at: t(2),
    created_at: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'courier-002',
    user_id: 'user-003',
    name: 'Ali Demir',
    phone: '+90 533 444 5566',
    vehicle_type: 'motorcycle',
    is_active: true,
    current_lat: 41.038,
    current_lng: 29.012,
    last_seen_at: t(5),
    created_at: new Date('2024-02-01').toISOString(),
  },
  {
    id: 'courier-003',
    user_id: 'user-004',
    name: 'Hasan Yıldız',
    phone: '+90 534 777 8899',
    vehicle_type: 'bicycle',
    is_active: false,
    current_lat: null,
    current_lng: null,
    last_seen_at: t(120),
    created_at: new Date('2024-02-15').toISOString(),
  },
];

export const mockOrders: OrderWithCourier[] = [
  {
    id: 'order-001',
    restaurant_id: 'rest-001',
    courier_id: 'courier-001',
    platform: 'yemeksepeti',
    platform_order_id: 'YS-8821943',
    customer_name: 'Ahmet Yılmaz',
    customer_address: 'Nispetiye Cad. 12/3, Etiler, İstanbul',
    customer_lat: 41.079,
    customer_lng: 29.035,
    status: 'picked_up',
    total_amount: 284.9,
    created_at: t(22),
    assigned_at: t(18),
    picked_up_at: t(8),
    delivered_at: null,
    courier: mockCouriers[0],
  },
  {
    id: 'order-002',
    restaurant_id: 'rest-001',
    courier_id: 'courier-002',
    platform: 'getir',
    platform_order_id: 'GT-4490217',
    customer_name: 'Zeynep Arslan',
    customer_address: 'Bağdat Cad. 88, Kadıköy, İstanbul',
    customer_lat: 40.9773,
    customer_lng: 29.0678,
    status: 'assigned',
    total_amount: 156.5,
    created_at: t(12),
    assigned_at: t(8),
    picked_up_at: null,
    delivered_at: null,
    courier: mockCouriers[1],
  },
  {
    id: 'order-003',
    restaurant_id: 'rest-001',
    courier_id: null,
    platform: 'trendyol',
    platform_order_id: 'TY-3301889',
    customer_name: 'Fatma Şahin',
    customer_address: 'Halaskargazi Cad. 55/7, Şişli, İstanbul',
    customer_lat: 41.062,
    customer_lng: 28.987,
    status: 'pending',
    total_amount: 89.9,
    created_at: t(5),
    assigned_at: null,
    picked_up_at: null,
    delivered_at: null,
    courier: null,
  },
  {
    id: 'order-004',
    restaurant_id: 'rest-001',
    courier_id: 'courier-001',
    platform: 'yemeksepeti',
    platform_order_id: 'YS-8819201',
    customer_name: 'Murat Öztürk',
    customer_address: 'Ihlamurdere Cad. 22, Beşiktaş, İstanbul',
    customer_lat: 41.0482,
    customer_lng: 29.0012,
    status: 'delivered',
    total_amount: 445.0,
    created_at: t(90),
    assigned_at: t(85),
    picked_up_at: t(72),
    delivered_at: t(45),
    courier: mockCouriers[0],
  },
  {
    id: 'order-005',
    restaurant_id: 'rest-001',
    courier_id: null,
    platform: 'pakettaksi',
    platform_order_id: 'PT-112934',
    customer_name: 'Selin Kara',
    customer_address: 'Teşvikiye Cad. 7/2, Nişantaşı, İstanbul',
    customer_lat: 41.0528,
    customer_lng: 28.9944,
    status: 'pending',
    total_amount: 210.0,
    created_at: t(3),
    assigned_at: null,
    picked_up_at: null,
    delivered_at: null,
    courier: null,
  },
  {
    id: 'order-006',
    restaurant_id: 'rest-001',
    courier_id: 'courier-002',
    platform: 'getir',
    platform_order_id: 'GT-4488901',
    customer_name: 'Emre Yılmaz',
    customer_address: 'Sinanpaşa Cad. 14, Beşiktaş, İstanbul',
    customer_lat: 41.046,
    customer_lng: 29.008,
    status: 'picked_up',
    total_amount: 127.5,
    created_at: t(35),
    assigned_at: t(30),
    picked_up_at: t(15),
    delivered_at: null,
    courier: mockCouriers[1],
  },
  {
    id: 'order-007',
    restaurant_id: 'rest-001',
    courier_id: null,
    platform: 'manual',
    platform_order_id: null,
    customer_name: 'Deniz Acar',
    customer_address: 'Ortabahçe Cad. 33, Beşiktaş, İstanbul',
    customer_lat: 41.0402,
    customer_lng: 29.005,
    status: 'pending',
    total_amount: 340.0,
    created_at: t(8),
    assigned_at: null,
    picked_up_at: null,
    delivered_at: null,
    courier: null,
  },
  {
    id: 'order-008',
    restaurant_id: 'rest-001',
    courier_id: 'courier-001',
    platform: 'trendyol',
    platform_order_id: 'TY-3298744',
    customer_name: 'Ayşe Güler',
    customer_address: 'Barbaros Bulvarı No:78, Balmumcu, İstanbul',
    customer_lat: 41.0511,
    customer_lng: 29.0108,
    status: 'delivered',
    total_amount: 195.0,
    created_at: t(120),
    assigned_at: t(115),
    picked_up_at: t(100),
    delivered_at: t(65),
    courier: mockCouriers[0],
  },
];
